openapi: 3.0.0
info:
  title: ''
  version: 1.0.0
  description: ''
paths:
  # healthCheck
  /api/health:
    get:
      tags:
        - Health Check
      summary: Health Check
      description: ''
      responses:
        200:
          description: Health Check Successful!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/healthCheckResponse'
        400:
          description: Bad request
        500:
          description: Internal Server Error
components:
  schemas:
    healthCheckResponse:
      properties:
        successful:
          type: boolean
          example: true
        message:
          type: string
          example: 'Server is up and running'
