version: '3.9'

services:
  node-rabbitmq-mysql:
    container_name: node-rabbitmq-mysql
    build:
      context: .
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: sh -c "until nc -z mysql 3306; do echo 'Waiting for MySQL...'; sleep 2; done; npm run start"
    environment:
      NODE_ENV: development
      PORT: 4000

      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: mysql
      TYPEORM_PORT: 3306
      TYPEORM_USERNAME: root
      TYPEORM_PASSWORD: password
      TYPEORM_DATABASE: test

      SECRET_KEY: secret
      EXPIRATION_TIME: 25m

      RABBITMQ_URL: amqp://user:pass@rabbitmq:5672

    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:8.0
    container_name: 'mysql'
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      start_interval: 5s
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  mysql:
  rabbitmq_data:
