version: '3.9'

services:
  node-rabbitmq-mysql-prod:
    container_name: node-rabbitmq-mysql-prod
    build:
      context: .
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    command: sh -c "until nc -z mysql 3306; do echo 'Waiting for MySQL...'; sleep 2; done; npm run start:prod"
    environment:
      NODE_ENV: production
      PORT: 4000

      DATABASE_URL: mysql://user:pass@mysql:3306/test_db

      RABBITMQ_URL: amqp://user:pass@rabbitmq:5672

    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_DATABASE: test_db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 5s
      start_interval: 5s
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  mysql:
  rabbitmq_data:
